language: node_js

node_js:
  - 'lts/*'

before_install:
  - npm i -g npm@6.4.1
  - npm i -g gulp-cli
  
cache: npm

branches:
  only:
    - master

script: gulp

before_deploy: "echo 'deploying'"

deploy:
  provider: npm
  email: "artem@dontsoft.com"
  api_key: "ea9b709f-8aff-42fd-9eed-06f1e241476e"
  skip_cleanup: true
  on:
    branch: master

after_deploy: "echo 'finished deploying'"