language: node_js
node_js:
- lts/*
before_install:
- npm i -g npm@6.4.1
- npm i -g gulp-cli
cache: npm
branches:
  only:
  - master
script: gulp
before_deploy: echo 'deploying'
deploy:
  provider: npm
  email: artem@dontsoft.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
after_deploy: echo 'finished deploying'
env:
  global:
  - secure: Gtsc1rAEcKJ4UXn6m01D5ZYRqPU6zweA/nCU5yaWusAezOMYLFtBD9wqFj7mhcsmmDxcAO2yFja8MiNK4EZ7EbjFN4kZnsJ0GF0s7c1SbA89LYxz1w4tgxAQ6EOXChNMibrMpatl99Q8yelmju5LPh5vh2tRm7fXD6qjviuXvIDe48qcrv1rVE9HzkoD2L5KaD1gz4DA+iJ90sm9MhruPDEPKHvr2veh6cDHn3/Zd2HJ/neDdstLssHVOdbKzXOoEIZjJ9DiHzg01lT6Jgx8RJcGTWfdDTvGxwfYdqj/oLQmLwlHXo6ThP29lFIq1n3cmfTnUWkACknPU8oUrBU/pgZJpYbGx3t9lRX5DCjKyoQOSTBb+LfnNjCrTb46nlf9VORbDXzErsqtYGj8E4LmqHMHfqtwpK9gnSqBiAEtCASt88+E1CP3ssHj49QPGmjzFuuqv79sM8SuS7GEo6fJNtT5BF05g7d+sdnxN9dUs4TGFH/vlVXokysNUjAn9e//+PtEKtKvGuT6LZd/LkzMaF+Klla3+RpBy3FKkNtowGGUyBct3OgSxtAOOfC0XbBkbRdxhmI+zK1qoO7Wk07B02YXogFPo+jtJCRAw6U/QUx9d0ceJpQ3Zlg1xIvybpK+6w5prEBtBj2UrimuIizousFdkqVsNN6yyp8ZLxHHoNA=
